[package]
name = "sol_world_messages"
version = "0.0.1"
edition = "2021"

[dependencies]
sol_voxel_lib = { path = "../voxel_lib", version = "*" }

serde = { version = "^1.0", features = ["derive"] }
typetag = "0.2"